import React from 'react';
import { CheckCircle2, AlertTriangle, AlertOctagon, HelpCircle, ShieldCheck, Stethoscope } from 'lucide-react';

const DISEASE_DETAILS = {
  Potato___healthy: {
    title: 'Healthy Potato Leaf',
    statusClass: 'disease-healthy',
    icon: CheckCircle2,
    color: '#10B981',
    description: 'No fungal or bacterial infection detected. The plant leaf shows robust health.',
    recommendations: [
      'Maintain standard watering schedule (avoid waterlogging).',
      'Ensure adequate sunlight and proper soil aeration.',
      'Perform regular weekly inspections for early pest detection.'
    ]
  },
  Potato___Early_blight: {
    title: 'Potato Early Blight',
    statusClass: 'disease-early',
    icon: AlertTriangle,
    color: '#F59E0B',
    description: 'Caused by the fungus Alternaria solani. Characterized by dark brown concentric rings on leaves.',
    recommendations: [
      'Apply protective copper-based or chlorothalonil fungicides.',
      'Remove and destroy infected lower leaves to reduce spore spread.',
      'Avoid overhead irrigation; water at the soil base to keep foliage dry.'
    ]
  },
  Potato___Late_blight: {
    title: 'Potato Late Blight',
    statusClass: 'disease-late',
    icon: AlertOctagon,
    color: '#EF4444',
    description: 'Caused by Phytophthora infestans. Highly destructive pathogen causing rapid leaf decay.',
    recommendations: [
      'Immediately isolate affected plants and remove severely blighted stems.',
      'Apply targeted systemic fungicides (e.g. Mancozeb / Metalaxyl).',
      'Ensure maximum spacing between plants to enhance air circulation.'
    ]
  }
};

export default function PredictionResult({ result, error }) {
  if (error) {
    return (
      <div className="glass-card" style={{ padding: '2rem', borderColor: 'rgba(239, 68, 68, 0.4)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', color: '#F87171', marginBottom: '1rem' }}>
          <AlertOctagon size={28} />
          <h3 style={{ fontSize: '1.25rem' }}>Prediction Failed</h3>
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>{error}</p>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="glass-card empty-state">
        <HelpCircle className="empty-icon" />
        <h3 style={{ fontSize: '1.2rem', marginBottom: '0.5rem', color: 'var(--text-main)' }}>
          No Prediction Yet
        </h3>
        <p>Upload a potato plant leaf image and click "Analyze Disease" to diagnose plant health.</p>
      </div>
    );
  }

  const details = DISEASE_DETAILS[result.class] || {
    title: result.class.replace(/_/g, ' '),
    statusClass: 'disease-early',
    icon: AlertTriangle,
    color: '#F59E0B',
    description: 'Diagnosis generated by trained AI vision model.',
    recommendations: ['Consult an agricultural expert for specific treatment advice.']
  };

  const IconComponent = details.icon;
  const confidencePercent = Math.round((result.confidence || 0) * 100);

  return (
    <div className="glass-card" style={{ padding: '1.75rem' }}>
      <div className="result-header">
        <h3 style={{ fontSize: '1.25rem' }}>Diagnosis Result</h3>
        <div className={`disease-badge ${details.statusClass}`}>
          <IconComponent size={20} />
          {details.title}
        </div>
      </div>

      <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', marginBottom: '1.25rem' }}>
        {details.description}
      </p>

      {/* Confidence Meter */}
      <div className="confidence-container">
        <div className="confidence-header">
          <span>AI Model Confidence</span>
          <span style={{ fontWeight: '700', color: 'var(--text-main)' }}>{confidencePercent}%</span>
        </div>
        <div className="confidence-bar-bg">
          <div
            className="confidence-bar-fill"
            style={{
              width: `${confidencePercent}%`,
              background: `linear-gradient(90deg, ${details.color}88 0%, ${details.color} 100%)`,
              boxShadow: `0 0 10px ${details.color}AA`
            }}
          />
        </div>
      </div>

      {/* Actionable Recommendations */}
      <div className="recommendations-box">
        <div className="rec-title">
          <Stethoscope size={18} style={{ color: details.color }} />
          Recommended Action & Treatment
        </div>
        <ul className="rec-list">
          {details.recommendations.map((rec, index) => (
            <li key={index} className="rec-item">
              {rec}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
